import typography from "@tailwindcss/typography"
import type { Config } from "tailwindcss"

export default {
  content: [
    "./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}",
    "./app/content/**/*.{md,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        blog: {
          bg: "#fafafa",
          text: "#1a1a1a",
          "bg-dark": "#0d0d0d",
          "text-dark": "#e8e8e8",
          accent: "#2563eb",
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
      animation: {
        "slow-pulse": "slowPulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        slowPulse: {
          "0%, 100%": { opacity: "0.1", transform: "scale(1.5)" },
          "50%": { opacity: "0.15", transform: "scale(1.7)" },
        },
      },
      scale: {
        "102": "1.02",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        ui: [
          "-apple-system",
          "BlinkMacSystemFont",
          "ui-sans-serif",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        serif: [
          "Charter",
          "Lora",
          "Iowan Old Style",
          "Apple Garamond",
          "Baskerville",
          "Times New Roman",
          "Droid Serif",
          "Times",
          "serif",
        ],
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      typography: () => ({
        blog: {
          css: {
            "--tw-prose-body": "#1a1a1a",
            "--tw-prose-headings": "#0a0a0a",
            "--tw-prose-lead": "#1a1a1a",
            "--tw-prose-links": "#2563eb",
            "--tw-prose-bold": "#0a0a0a",
            "--tw-prose-counters": "#525252",
            "--tw-prose-bullets": "#a3a3a3",
            "--tw-prose-hr": "#e5e5e5",
            "--tw-prose-quotes": "#0a0a0a",
            "--tw-prose-quote-borders": "#2563eb",
            "--tw-prose-captions": "#525252",
            "--tw-prose-code": "#0a0a0a",
            "--tw-prose-pre-code": "#e8e8e8",
            "--tw-prose-pre-bg": "#0d0d0d",
            "--tw-prose-th-borders": "#d4d4d4",
            "--tw-prose-td-borders": "#e5e5e5",
            "--tw-prose-invert-body": "#e8e8e8",
            "--tw-prose-invert-headings": "#fafafa",
            "--tw-prose-invert-lead": "#e8e8e8",
            "--tw-prose-invert-links": "#60a5fa",
            "--tw-prose-invert-bold": "#fafafa",
            "--tw-prose-invert-counters": "#a3a3a3",
            "--tw-prose-invert-bullets": "#525252",
            "--tw-prose-invert-hr": "#262626",
            "--tw-prose-invert-quotes": "#fafafa",
            "--tw-prose-invert-quote-borders": "#60a5fa",
            "--tw-prose-invert-captions": "#a3a3a3",
            "--tw-prose-invert-code": "#fafafa",
            "--tw-prose-invert-pre-code": "#e8e8e8",
            "--tw-prose-invert-pre-bg": "#0d0d0d",
            "--tw-prose-invert-th-borders": "#404040",
            "--tw-prose-invert-td-borders": "#262626",
            maxWidth: "65ch",
            lineHeight: "1.7",
            fontSize: "1.0625rem",
          },
        },
      }),
    },
  },
  plugins: [typography],
} satisfies Config
